### ISSUE TITLE
rpm-ostree missing

### ISSUE THREAD

**Issue by chrias** [containers/podman-wsl-fedora#16]
I need to run an armhf container, i saw this comment mentioning the installation of `qemu-user-static` via `rpm-ostree` for using images with other architectures https://github.com/containers/podman/issues/17267#issuecomment-1408106579

### Steps to reproduce the issue
1. podman machine init
2. podman machine ssh
3. run rpm-ostree, `-bash: rpm-ostree: command not found`

**Comment by chrias** [comment]
edit: i didn't check the release notes of v38

**Comment by gbraad** [comment]
Not sure which release notes you refer to. This image for use with WSL2 is not based on FCOS (so there are no ostree layers) as in the issue you refer to.
